### ISSUE TITLE
Give Local Support. Not only Chinies 

### ISSUE THREAD

**Issue by STPLAmrut** [loper7/DateTimePicker#74]

**Comment by loper7** [comment]
Happy chinese new year~
[CardDatePickerDialog](https://github.com/loperSeven/DateTimePicker/wiki/CardDatePickerDialog-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E) in the project is just an example，all other components should be international,if there are other issues, please point out（The above content is from google translation, please understand if there is any problem）
