### ISSUE TITLE
这里没看懂，可以解释一下吗

### ISSUE THREAD

**Issue by powerzd** [loper7/DateTimePicker#78]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/20632944/225271101-818488e4-b2f9-42cf-be4a-cbabfc98a08e.png">
小写view作为tag会有问题，没办法通过编译啊，我尝试将view改为View，使用的时候会抛出异常
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/20632944/225272103-8bba2c00-dfa7-41f6-bdb5-ce71171dbdda.png">

**Comment by loper7** [comment]
这是使用自定义view的一种方法，studio可能会报红但是不会影响编译运行

**Comment by powerzd** [comment]
Android Studio Giraffe | 2022.3.1 Canary 8 无法通过编译

**Comment by loper7** [comment]
我使用2022.1.1 Patch 1 是没有问题的，需要注意你项目本身有没有引用android.widget.numberpicker类。
如果实在不行，可以直接将该xml删除  在numberPicker中修改相关代码自行创建mSelectedText，例如：
```
 // input text
        mSelectedText = new EditText(context);
        mSelectedText.setLayoutParams(new LayoutParams(LayoutParams.MATCH_PARENT,LayoutParams.WRAP_CONTENT));
        mSelectedText.setGravity(Gravity.CENTER);
        mSelectedText.setSingleLine(true);
        mSelectedText.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);
        mSelectedText.setEnabled(false);
        mSelectedText.setFocusable(false);
        mSelectedText.setVisibility(View.INVISIBLE);
        mSelectedText.setImeOptions(EditorInfo.IME_ACTION_NONE);
```

**Comment by tr15tan** [comment]
> 我使用2022.1.1 Patch 1 是没有问题的，需要注意你项目本身有没有引用android.widget.numberpicker类。 如果实在不行，可以直接将该xml删除 在numberPicker中修改相关代码自行创建mSelectedText，例如：
> 
> ```
>  // input text
>         mSelectedText = new EditText(context);
>         mSelectedText.setLayoutParams(new LayoutParams(LayoutParams.MATCH_PARENT,LayoutParams.WRAP_CONTENT));
>         mSelectedText.setGravity(Gravity.CENTER);
>         mSelectedText.setSingleLine(true);
>         mSelectedText.setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);
>         mSelectedText.setEnabled(false);
>         mSelectedText.setFocusable(false);
>         mSelectedText.setVisibility(View.INVISIBLE);
>         mSelectedText.setImeOptions(EditorInfo.IME_ACTION_NONE);
> ```

请问要如何引入 android.widget.numberpicker 类？我看 date_time_picker 这个 module 的 build.gradle 中也没有进行什么引入呀，只有一个 `com.google.android.material:material:1.3.0` ，我项目本身也是添加了这个库的（应该和这个没有关系吧）。自行创建的mSelectedText 我试过了是可行的。
