### ISSUE TITLE
这东西真好用

### ISSUE THREAD

**Issue by xtgadw** [loper7/DateTimePicker#80]
1. Wiki  - >   CardDatePickerDialog 使用说明  - >  所有可配置属性 setAssistColor 多了一个右括号
2.希望下面的 setDisplayType 也添加注释 DateTimeConfig.YEAR, DateTimeConfig.MONTH...
3.showFocusDateInfo 为 true 时，没有跟 setDisplayType 联动，不清楚有没有这样的需求，只是看到提一下
4.这东西真好用

**Comment by loper7** [comment]
感谢你的建议，wiki的错误和补充已经处理了，第三条后续考虑加上，dialog本身的意义主要对picker的实践😊
