### ISSUE TITLE
作者是否可以将DateTimePicker改为open class呢？

### ISSUE THREAD

**Issue by liyuhaolol** [loper7/DateTimePicker#82]
因为class类在kotlin里被视为final类型，我们这边不能再次继承这个类，进行我们自己的修改了，反而NumberPicker就是一个public class的类，我们就能继承。如果想要继承DateTimePicker，我们还要下载源码，导入到项目里，自己加open，这样未免也太不友好了，希望作者可以改一下，kotlin全都加open，这样让我们使用起来容易一点。

**Comment by liyuhaolol** [comment]
- 对了额外提一个建议，比如`NumberPicker`里的`setSelectedTextColor`,`setDividerColor`此类的方法，如果Picker已经被显示，调用这两个方法，颜色不会被立刻重绘，需要在方法最后加入`invalidate();`让View立刻进行重绘。范例：
```java
    public void setSelectedTextColor(@ColorInt int color) {
        mSelectedTextColor = color;
        mSelectedText.setTextColor(mSelectedTextColor);
        invalidate();//加在这里让View重绘
    }
```
- 具体的需求场景，当Picker正在显示的时候，发生了手机的深浅色（颜色）切换，App跟随系统变换时，Picker无法进行预计的颜色变换，因为Picker已经被绘制，但是调用的方法没有调用`invalidate();`强制让View进行重绘导致的。所以推荐作者能将此类方法都加入`invalidate();`来进行View的重绘。
- 目前因为上述提到的这些问题，所以只能调用作者源码进行使用，相对麻烦一点。如果作者能完善此类问题，以后直接通过jitpack依赖，会让代码少很多，也容易一些。

**Comment by loper7** [comment]
👍非常棒的建议，如果方便可以直接fork然后提pr😊

**Comment by loper7** [comment]
已处理
