### ISSUE TITLE
此项目每次更新后，是不是在仓库中移除了旧版本

### ISSUE THREAD

**Issue by wwxwwq** [loper7/DateTimePicker#83]
之前项目里用的0.5.4的版本，用了一段时间，换新电脑运行项目，发包此依赖外下载不下来；后面就升级到了0.6.0版本；最近在配置jenkins自动构建，又发现0.6.0的包又下载不下来了，换成0.6.2就可以了；请问一下，是不是每次更新了版本，旧版本就从仓库中移除了，导致无法通过gradle下载下来；

**Comment by loper7** [comment]
项目自动托管到 jitpack，不会删除历史版本。
![image](https://github.com/loper7/DateTimePicker/assets/20430552/eac8151a-24d5-448d-8f8c-2c78daa2c2bd)

**Comment by loper7** [comment]
可以通过[jitpack](https://www.jitpack.io/#loper7/DateTimePicker)查看每个版本以及齐构建信息
